name = "Botiga AI Sales Assistant"
client_id = "9024718457c9563257b14484174b9e32" # The currently active app in dev.shopify.com
application_url = "https://botiga-api-two.vercel.app/api/shopify/auth"
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "jxavr1-ur.myshopify.com"

[access_scopes]
scopes = "write_price_rules,write_discounts,read_products,write_draft_orders"

[auth]
redirect_urls = [
  "https://botiga-api-two.vercel.app/api/shopify/callback",
  "http://localhost:3001/api/shopify/callback"
]

[webhooks]
api_version = "2024-01"

  [[webhooks.subscriptions]]
  topics = ["app/uninstalled"]
  uri = "https://botiga-api-two.vercel.app/webhooks/app/uninstalled"

  [webhooks.privacy_compliance]
  customer_data_request_url = "https://botiga-api-two.vercel.app/webhooks/customers/data_request"
  customer_deletion_url = "https://botiga-api-two.vercel.app/webhooks/customers/redact"
  shop_deletion_url = "https://botiga-api-two.vercel.app/webhooks/shop/redact"

[pos]
embedded = false
