api_version = "2024-01"
uid = "bb90845b-fbe1-39cb-881c-971ebfbf8857ac338048"

[[extensions]]
type = "theme"
name = "Botiga Negotiation Widget"
handle = "botiga-widget"

  [extensions.development]
  resource = "/products"
  preview_url = "https://botiga-api-two.vercel.app"
